# Generated by Django 2.1.5 on 2019-02-16 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190216_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='author_name',
        ),
    ]
