# Generated by Django 2.1.5 on 2019-02-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=50)),
                ('review_count', models.IntegerField(default=0, verbose_name='Number of Reviews')),
                ('bio', models.TextField(default=models.CharField(default='Name', max_length=50), max_length=500, verbose_name='About me')),
                ('genre', models.CharField(choices=[('FA', 'Fantasy'), ('RO', 'Romance'), ('TR', 'Thriller'), ('MY', 'Mystery'), ('BI', 'Biography'), ('FI', 'Fiction'), ('NF', 'Non Fiction'), ('SF', 'Science Fiction')], default='FA', max_length=2)),
            ],
        ),
    ]
