# Generated by Django 2.1.5 on 2019-02-20 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='image_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='author',
            name='numFollowers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='review',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
