# Generated by Django 2.1.5 on 2019-02-21 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190216_2306'),
        ('qanswers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.Book'),
            preserve_default=False,
        ),
    ]
